##
## Config file for snakemake CNV callers benchmarking workflow using bowtie2-picard-gatk3 alignment 
##

## Fasta
human_reference: /ingemm/ref/Ref/hg19/fasta/ucsc.hg19.fasta

## Bed taget
exome_bed: /ingemm/scratch/TFM/CNV/BEDs/IDT_xgen-exome-research-panel-v2-targets-hg19.bed
lacon_exome_bed : /ingemm/scratch/TFM/CNV/TFM_borrador/algorithms/tools/laconv/exome_bed/240722_Exomas_annotated_for_coverage.bed
exomedepth_bed : /ingemm/scratch/TFM/CNV/BEDs/old_beds/IDT_xgen-exome-research-panel-v2-targets-hg19.bed

# lacon files
lacon_config : /ingemm/scratch/TFM/CNV/TFM_borrador/algorithms/tools/laconv/config_hg19.cfg

# cnvkit files
refFlat: /ingemm/scratch/TFM/CNV/TFM_borrador/algorithms/tools/cnvkit/refFlat.txt
bed_mappable: /ingemm/scratch/TFM/CNV/TFM_borrador/algorithms/tools/cnvkit/access-5k-mappable.hg19.bed


## Aligment
alignment_dir: /ingemm/scratch/TFM/CNV/alignment
sonda : IDT-V2
alignment: bowtie2-picard-gatk3

## Gold standard
gold_standard_general : /ingemm/scratch/TFM/CNV/TFM_borrador/gold_standard/HG001/final_gold_standard/general/gold_standard_general_IDTv2.vcf
gold_standard_pass : /ingemm/scratch/TFM/CNV/TFM_borrador/gold_standard/HG001/final_gold_standard/pass/gold_standard_pass_IDTv2.vcf

## Directories 
singularity_dir : /ingemm/scratch/TFM/CNV/TFM_borrador/algorithms/imagenes
tools_dir: /ingemm/scratch/TFM/CNV/TFM_borrador/algorithms/tools/
pipeline_dir: /ingemm/scratch/TFM/CNV/TFM_borrador/algorithms/pipeline
ss_samples: /ingemm/scratch/TFM/CNV/TFM_borrador/algorithms/pipeline/configuraciones/IDT-V2/ss_hg19.txt
ss_controls: /ingemm/scratch/TFM/CNV/TFM_borrador/algorithms/pipeline/configuraciones/IDT-V2/ss_hg19_controles.txt
results_dir: /ingemm/scratch/TFM/CNV/TFM_borrador/algorithms/results
results_process_dir: /ingemm/scratch/TFM/CNV/TFM_borrador/algorithms/results_posprocess

